version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MYSQL_DATABASE: JourneyDb
      MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD # Пароль суперпользователя
      MYSQL_USER: YOUR_USER                   # Создать пользователя mikser
      MYSQL_PASSWORD: YOUR_USER_PASSWORD   # Пароль для mikser
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env  # Docker Compose сам прочитает файл и передаст переменные в контейнер
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3031:3031"
    environment:
      - DB_HOST=db
      - DB_USER=YOUR_USER
      - DB_PASSWORD=YOUR_USER_PASSWORD
      - DB_NAME=JourneyDb
      - DB_PORT=3306
      - PORT=3031
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://backend:3031
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3030:3030"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3031
    networks:
      - app-network
    depends_on:
      - backend

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  chroma_data:
