version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MYSQL_DATABASE: JourneyDb
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env  # Docker Compose сам прочитает файл и передаст переменные в контейнер
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3031:3031"
    environment:
      - DB_HOST=db
      - DB_USER=mikser
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - DB_NAME=JourneyDb
      - PORT=3031
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
    env_file:
      - .env  # Docker Compose сам прочитает файл и передаст переменные в контейнер
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3030:3030"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://ai-nvkz.ru:3031
    depends_on:
      - backend

volumes:
  mysql_data:
